# Generated by Django 4.2.6 on 2023-10-14 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='S3Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_key', models.CharField(max_length=255)),
                ('secret_key', models.CharField(max_length=255)),
                ('bucket_name', models.CharField(blank=True, max_length=64, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('folder_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
