# Generated by Django 4.2.6 on 2023-10-17 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0002_typemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
    ]
