# Generated by Django 4.2.6 on 2023-10-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0003_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='s3object',
            name='extension',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
