# Generated by Django 4.2.6 on 2023-10-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0004_s3object_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='extension',
            name='ext',
            field=models.CharField(default='.', help_text="Include '.' in the extension", max_length=12),
        ),
    ]
