# Generated by Django 4.2.6 on 2023-10-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0005_extension_ext'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnowflakeObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sfUrl', models.CharField(max_length=255)),
                ('sfAccount', models.CharField(max_length=255)),
                ('sfUser', models.CharField(max_length=255)),
                ('sfPassword', models.CharField(max_length=255)),
                ('sfDatabase', models.CharField(max_length=255)),
                ('sfSchema', models.CharField(max_length=255)),
                ('sfWarehouse', models.CharField(max_length=255)),
                ('dbTable', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
