# Generated by Django 4.2.6 on 2023-10-25 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0007_client_clientuserprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='extension',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aws.client'),
        ),
        migrations.AddField(
            model_name='s3object',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aws.client'),
        ),
        migrations.AddField(
            model_name='snowflakeobject',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aws.client'),
        ),
        migrations.AddField(
            model_name='typemodel',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aws.client'),
        ),
    ]
