# Generated by Django 4.2.6 on 2024-03-01 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0008_extension_client_s3object_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snowflakeobject',
            name='dbTable',
        ),
    ]
